"""add chart_data to chat_messages

Revision ID: 0d057fc024ba
Revises: b3567f74d513
Create Date: 2026-09-15 18:47:36.354362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d057fc024ba'
down_revision: Union[str, Sequence[str], None] = 'b3567f74d513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('chart_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'chart_data')
    # ### end Alembic commands ###
