"""add additional_context to business_profiles

Revision ID: 143bc8909ee1
Revises: 5d47e408fd8f
Create Date: 2026-09-16 14:25:19.347896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143bc8909ee1'
down_revision: Union[str, Sequence[str], None] = '5d47e408fd8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_profiles', sa.Column('additional_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('business_profiles', 'additional_context')
    # ### end Alembic commands ###
