"""initial schema: projects, business_profiles

Revision ID: 5cf10ea6e8e6
Revises: 
Create Date: 2026-08-18 20:35:22.630766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf10ea6e8e6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('raw_user_input', sa.Text(), nullable=False),
    sa.Column('detected_language', sa.String(length=16), nullable=False),
    sa.Column('output_language', sa.String(length=16), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=False),
    sa.Column('business_description_source', sa.String(length=16), nullable=False),
    sa.Column('target_market_description', sa.Text(), nullable=False),
    sa.Column('target_market_description_source', sa.String(length=16), nullable=False),
    sa.Column('target_market_geography', sa.Text(), nullable=False),
    sa.Column('target_market_geography_source', sa.String(length=16), nullable=False),
    sa.Column('business_model_type', sa.Text(), nullable=False),
    sa.Column('business_model_type_source', sa.String(length=16), nullable=False),
    sa.Column('capex_amount', sa.Float(), nullable=False),
    sa.Column('capex_currency', sa.String(length=8), nullable=False),
    sa.Column('capex_source', sa.String(length=16), nullable=False),
    sa.Column('capex_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('opex_monthly_amount', sa.Float(), nullable=False),
    sa.Column('opex_monthly_currency', sa.String(length=8), nullable=False),
    sa.Column('opex_monthly_source', sa.String(length=16), nullable=False),
    sa.Column('opex_monthly_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('pricing_unit_price', sa.Float(), nullable=False),
    sa.Column('pricing_currency', sa.String(length=8), nullable=False),
    sa.Column('pricing_source', sa.String(length=16), nullable=False),
    sa.Column('pricing_model', sa.Text(), nullable=False),
    sa.Column('pricing_model_source', sa.String(length=16), nullable=False),
    sa.Column('expected_monthly_sales', sa.Float(), nullable=True),
    sa.Column('expected_monthly_sales_source', sa.String(length=16), nullable=False),
    sa.Column('expected_monthly_sales_low_confidence', sa.Boolean(), nullable=False),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('team_size_source', sa.String(length=16), nullable=True),
    sa.Column('analysis_horizon_years', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_profiles')
    op.drop_table('projects')
    # ### end Alembic commands ###
