"""add study_type and requested_phase to study_results

Revision ID: b3567f74d513
Revises: d09dbe9c80ba
Create Date: 2026-09-15 13:25:11.455104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3567f74d513'
down_revision: Union[str, Sequence[str], None] = 'd09dbe9c80ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_results', sa.Column('study_type', sa.String(length=16), server_default='full', nullable=False))
    op.add_column('study_results', sa.Column('requested_phase', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_results', 'requested_phase')
    op.drop_column('study_results', 'study_type')
    # ### end Alembic commands ###
