"""add glossary cache table

Revision ID: dec34c97004c
Revises: d27c8bf42baa
Create Date: 2026-08-29 16:29:17.181350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec34c97004c'
down_revision: Union[str, Sequence[str], None] = 'd27c8bf42baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_cache',
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('terms', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glossary_cache')
    # ### end Alembic commands ###
